- name: Update Dynamic DNS Record
  hosts: localhost
  gather_facts: false

  # Load the encrypted credentials for UltraDNS.
  vars_files:
    - ~/ansible/ultra_vault.yml

  tasks:
    # Retrieve the public-facing IP address of the machine.
    - name: Get current public IP
      uri:
        url: http://icanhazip.com # Simple service that returns the public IP.
        return_content: yes
      register: public_ip # Store the result for later use.

    # Remove any leading/trailing whitespace from the retrieved IP address.
    - name: Sanitize public IP
      set_fact:
        sanitized_ip: "{{ public_ip.content | trim }}"

    # Update the A record for the specified hostname to reflect the current IP.
    - name: Update A record with current IP (only if changed)
      ultradns.ultradns.record:
        zone: example.com.
        name: ddns
        type: A
        data: "{{ sanitized_ip }}" # The current public IP.
        ttl: 300
        solo: true # Ensures only one A record exists for this hostname.
        state: present
        provider: "{{ ultra_provider }}"