---
# This role will handle the setup of Docker on the host machine. If Docker is
# already installed, or if you prefer to handle the installation manually,
# leave this section commented out.
#
# For more information see: 
#   - https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/docker/
#
# - name: Run Docker Setup On Host
#   hosts: localhost
#   gather_facts: yes
#   become: yes

#   roles:
#     - role: geerlingguy.docker
#       vars:
#         docker_edition: 'ce'
#         docker_service_state: started
#         docker_service_enabled: true
#         docker_packages:
#           - "docker-{{ docker_edition }}"
#           - "docker-{{ docker_edition }}-cli"
#           - "docker-{{ docker_edition }}-rootless-extras"
#         docker_packages_state: present
#         docker_install_compose_plugin: true
#         docker_compose_package: docker-compose-plugin
#         docker_compose_package_state: present
#         docker_users:
#           - "{{ ansible_user }}"

# This role will handle the setup of the XRR client
- name: Create Expiring Resource Records
  hosts: localhost
  gather_facts: no

  roles:
    - role: ultradns.dnsops.create_xrr
      vars:
        xrr_base_dir: "~/xrr_records" # Directory to create for Docker files
        records: # List of records to add
          - name: "{{ test_host_name }}-temp"
            type: "TXT"
            data: "Temporary record"
            ttl: 300
            zone: "{{ test_zone_name }}"
          - name: "{{ test_host_name }}-temp"
            type: "A"
            data: "192.168.1.100"
            ttl: 300
            zone: "{{ test_zone_name }}"
        expire_in: "10m" # Expire time in minutes (m), hours (h), days (d), weeks (w), or months (M)
        vault_file: "../group_vars/test_servers/vault" # Path to the vault file
        vault_pass_file: "~/.vault-password" # Path to the vault password file