- name: Manage UltraDNS Zone
  hosts: localhost
  gather_facts: false

  # Load the encrypted credentials from an Ansible Vault file.
  vars_files:
    - ~/ansible/ultra_vault.yml

  tasks:
    # Create a primary DNS zone in UltraDNS.
    # This ensures that `example.com.` exists in your UltraDNS account.
    - name: Create an UltraDNS primary zone
      ultradns.ultradns.zone:
        name: example.com. # The fully qualified domain name (FQDN) of the zone.
        account: myaccount # The UltraDNS account to associate the zone with.
        state: present # Ensures the zone is created if it doesn't exist.
        provider: "{{ ultra_provider }}" # Uses authentication details from the Vault file.