- name: Test Playbook
  hosts: test_servers
  become: false  # No sudo needed for these checks

  tasks:
    # Check if Python is installed by running `python3 --version`
    # The output of this command is stored in the `python_version` variable.
    - name: Check if Python is installed
      shell: python3 --version
      register: python_version
      changed_when: false  # Prevents Ansible from thinking this task makes changes

    # Print the detected Python version using Ansible's debug module.
    - name: Print Python version
      debug:
        msg: "Python version installed: {{ python_version.stdout }}"